# Site settings
title: Stephen Herko
tagline: Creative Director
email: hello@stephenherko.com
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stephenherko.com" # the base hostname & protocol for your site
twitter: stephenherko
github: stephenherko
permalink: /:title

# Build settings
markdown: kramdown
