# Site settings
title: Stephen Herko
tagline: Creative Director
email: hello@stephenherko.com
description: "I'm interested in skillsets like Branding, Front End Development, and Design. I love helping brands reach and develop their voice."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://stephenherko.com" # the base hostname & protocol for your site
twitter: stephenherko
github: stephenherko
permalink: /:title

# Build settings
markdown: kramdown
